SELECT NAME FROM INMATES
WHERE DAYSUNTILRELEASE = 9
OR DAYSUNTILRELEASE = 12
OR DAYSUNTILRELEASE = 15
OR DAYSUNTILRELEASE = 16
OR DAYSUNTILRELEASE = 24
OR DAYSUNTILRELEASE = 31
OR DAYSUNTILRELEASE = 40