SELECT MORNINGMOOD,
CASE 
    WHEN MORNINGMOOD < 3 THEN 'BAD'
    WHEN MORNINGMOOD >= 3 AND MORNINGMOOD < 6 THEN 'OKAY'
    WHEN MORNINGMOOD >= 6 AND MORNINGMOOD < 8 THEN 'GOOD'
    WHEN MORNINGMOOD >= 8 THEN 'EXCELLENT'
END AS MORAL,
COUNT(*) AS MORALITYCOUNTER
FROM MOODOFCREW
GROUP BY MORAL