DROP TABLE IF EXISTS WORKER;

CREATE TABLE WORKER (
    WORKER_ID   INTEGER      PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR (30),
    FIRSTNAME   VARCHAR (30),
    HARVESTRATE DECIMAL,
    LOAN        DECIMAL
);