-- SQLite
-- SQLite
SELECT NAME,LOCATION,ENTRY,ENTRYREASON FROM INBOUNDS;
SELECT NAME,ENTRY FROM INBOUNDS;
SELECT INCOME - COST AS PROFIT,PUNISHMENT FROM PUNISHMENT;
SELECT INCOME - COST as PROFIT, 
    PUNISHMENT,
    (CASE WHEN INCOME - COST < 0 THEN 
        'LOSS' 
     ELSE 
        'PROFIT' 
     END) AS 'PROFIT STATUS'
FROM PUNISHMENT;

SELECT PUNISHMENT,
    (CASE 
        WHEN INCOME-COST <0 THEN 'LOSS'
        WHEN INCOME-COST >0 THEN 'PROFIT'
    ELSE
        'NO LOSS NO PROFIT'
    END) AS 'PROFIT STATUS'

FROM PUNISHMENT;