DROP TABLE IF EXISTS PLANT;

CREATE TABLE PLANT(
    PLANT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SUGARTYPE INTEGER,
    HARVESTAMOUNT DECIMAL,
    FIELD INTEGER   
);


DROP TABLE IF EXISTS WORKER;

CREATE TABLE WORKER(
    WORKER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30),
    FIRSTNAME VARCHAR(30),
    HARVESTRATE DECIMAL,
    LOAN DECIMAL,
    FIELD INTEGER
);

DROP TABLE IF EXISTS SUGARBAG;

CREATE TABLE SUGARBAG(
    SUGARBAG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIELD INTEGER,
    WORKER INTEGER,
    SUGARTYPE VARCHAR(30),
    AMOUNT INTEGER
);

DROP TABLE IF EXISTS FIELD;

CREATE TABLE FIELD(
    FIELD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30)
);

DROP TABLE IF EXISTS SUGARTYPE;

CREATE TABLE SUGARTYPE(
    SUGARTYPE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30)
);