SELECT COMMITTED_CRIMES.*,
       INBOUNDS.*
  FROM COMMITTED_CRIMES
       LEFT JOIN
       INBOUNDS ON COMMITTMENT_DATE = ENTRY_DATE
       
UNION

SELECT COMMITTED_CRIMES.*,
       INBOUNDS.*
  FROM INBOUNDS
       LEFT JOIN
       COMMITTED_CRIMES ON COMMITTMENT_DATE = ENTRY_DATE;
