SELECT 
    BELONGSTO
    , KINDOFRUM
    , SUM(VALUE)AS SELLPRICE
    , HIDINGTAXES
    , ROUND(SUM(VALUE*(HIDINGTAXES/100)),2) AS PADREPAYOUT
    , ROUND(SUM(VALUE*(HIDINGTAXES/100)*0.2),2) AS CUTOFF
    , COUNT(*) AS BARRELS
FROM RUMHIDEOUT 
GROUP BY BELONGSTO, KINDOFRUM
